Evaluate fashion_mnist

1.First step: load data and check data,split to train and test

2.Second Step: check and do some research on how many common classifiers

3.Third Step: work around these candidate algorithms to see the performance 

In [48]:
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

In [50]:
((X_train, y_train),(X_test, y_test))= fashion_mnist.load_data()

In [ ]:
#数据处理
#since scikit-learn only expects 2d data,we reshape 3d data to 2d data
nsample, nx, ny = X_train.shape
X_new_train = X_train.reshape(nsample, nx*ny)
#对data进行feature Scaling
scaler = StandardScaler().fit(X_new_train)
X_new = scaler.transform(X_new_train)
x1,x2 = X_new_train.shape

First Starting from very simple Algorithm: Logistic Regression

In [85]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
log_clf = LogisticRegression(solver = "lbfgs", max_iter =10000)
log_clf.fit(X_new, y_train)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[-0.00864371 -0.02322333 -0.03917806 ... -0.15681128 -0.08967308
  -0.03414729]
 [-0.00864371 -0.02322333 -0.03917806 ... -0.15681128 -0.08967308
  -0.03414729]
 [-0.00864371 -0.02322333 -0.03917806 ... -0.15681128 -0.08967308
  -0.03414729]
 ...
 [-0.00864371 -0.02322333 -0.03917806 ... -0.15681128 -0.08967308
  -0.03414729]
 [-0.00864371 -0.02322333 -0.03917806 ... -0.15681128 -0.08967308
  -0.03414729]
 [-0.00864371 -0.02322333 -0.03917806 ... -0.15681128 -0.08967308
  -0.03414729]]


LogisticRegression(max_iter=10000)

In [86]:
nsample, nx, ny = X_train.shape
#since scikit-learn only expects 2d data,we reshape 3d data to 2d data
X_new_train = X_train.reshape(nsample, nx*ny)
ntest, tx, ty = X_test.shape
X_new_test = X_test.reshape(ntest,tx*ty)


In [90]:
y_pred = log_clf.predict(X_new_test)
#通过比较y_pred和y_test来计算准确率
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.725

Second I will try the K - Nearest Neighbors Classifier

In [82]:
from sklearn.neighbors import KNeighborsClassifier
knn_clf = KNeighborsClassifier(n_neighbors = 8)
knn_clf.fit(X_new_train, y_train)
y_pred = knn_clf.predict(X_new_test)

In [84]:
#通过比较y_pred和y_test来计算准确率
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.8534

3. Decision Tree Classfier

In [93]:
from sklearn.tree import DecisionTreeClassifier
tree_clf = DecisionTreeClassifier(criterion = "entropy", splitter = "best", max_depth = 10)
tree_clf.fit(X_new_train, y_train)
y_pred = tree_clf.predict(X_new_test)



In [94]:
accuracy_score(y_pred, y_test)

0.8107

4.Support Vector Machine支持向量机

In [95]:
from sklearn.svm import SVC
svc = SVC(kernel = "rbf")
svc.fit(X_new_train, y_train)



In [98]:
y_pred = svc.predict(X_new_test)
accuracy_score(y_pred, y_test)

0.8828

In [97]:
accuracy_score(y_pred, y_test)

0.8828